### ISSUE TITLE
jose-elias-alvarez/null-ls.nvim ist nicht maintained

### ISSUE THREAD

**Issue by chocoladisco** [malte-soe/dotfiles#13]
@malte-soe können uns mal überlegen was für Alternative wir in Zukunft verwenden:

https://github.com/sbdchd/neoformat

oder 

https://github.com/mhartington/formatter.nvim

**Comment by malte-soe** [comment]
Ah nice catch, thanks! Replaced it with https://github.com/nvimtools/none-ls.nvim
